import {
    codeStyle,
    comments,
    defineConfig,
    ignores,
    imports,
    javaScript,
    jsDoc,
    jsonc,
    jsx,
    markdown,
    react,
    regexp,
    tailwindcss,
    toml,
    typeScript,
    yaml,
} from "@withsprinkles/eslint-config";

export default defineConfig({
    plugins: [
        codeStyle(),
        comments(),
        ignores([
            "**/eslint.config.ts",
            "**/worker-configurtion.d.ts",
            "**/public/**",
            "**/*.{png,jpg,jpeg,webp,svg}",
        ]),
        imports(),
        javaScript(),
        typeScript({ tsconfigPath: "./tsconfig.json" }),
        jsDoc(),
        jsonc(),
        jsx(),
        markdown(),
        react({
            useReactCompiler: false,
            tsconfigPath: "./tsconfig.json",
        }),
        regexp(),
        tailwindcss({ stylesheet: "./app/styles/style.css" }),
        toml(),
        yaml(),
    ],
});
