[tools]
node = "lts"

[tasks]
dev.run = "npx react-router dev --host"
build.run = "npx react-router build"
preview.depends = "build"
preview.run = "npx vite preview"

deploy.depends = "build"
deploy.run = "npx wrangler deploy"

fmt.run = "npx prettier -w ."

"typegen:cloudflare".run = "npx wrangler types"
"typegen:react-router".run = "npx react-router typegen"

typecheck.depends = "typegen:*"
typecheck.run = "npx tsgo --noEmit"
