// Generated by scripts/build-icons.mjs — do not edit by hand.
export type IconName =
    | "book"
    | "calendar"
    | "dining"
    | "movie"
    | "movie-camera"
    | "playback-play-button"
    | "pop-out"
    | "tv";
