// Generated by scripts/build-icons.ts — do not edit by hand.
export type IconName =
    | "book"
    | "calendar"
    | "close"
    | "dining"
    | "movie"
    | "movie-camera"
    | "playback-play-button"
    | "pop-out"
    | "search"
    | "sliders-vertical"
    | "tv";
