// Builds a lean Primaries sprite subset (app/assets/primaries.svg) + its name type
// (app/components/icon-names.ts) from the full sprite vendored at scripts/primaries-full.svg.
//
// To add an icon: add its symbol id to ICONS below, then run `mise run icons`
// (or `node scripts/build-icons.mjs`). To regenerate from a newer upstream sprite,
// pass its path as the first CLI arg or via the PRIMARIES_SRC env var.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// The icon names actually used in the app. Keep this list minimal.
const ICONS = [
    "tv",
    "movie-camera",
    "movie",
    "calendar",
    "dining",
    "book",
    "playback-play-button",
    "pop-out",
];

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source =
    process.argv[2] ?? process.env.PRIMARIES_SRC ?? resolve(repoRoot, "scripts/primaries-full.svg");

const spriteOut = resolve(repoRoot, "app/assets/primaries.svg");
const typeOut = resolve(repoRoot, "app/components/icon-names.ts");

let full;
try {
    full = readFileSync(source, "utf8");
} catch {
    console.error(`Cannot read upstream sprite at: ${source}`);
    console.error("Pass the path as an argument or set PRIMARIES_SRC.");
    process.exit(1);
}

const names = [...new Set(ICONS)].sort();
const symbols = [];
const missing = [];
for (const name of names) {
    const match = full.match(new RegExp(`<symbol id="${name}"[\\s\\S]*?</symbol>`));
    if (match) symbols.push(match[0].trim());
    else missing.push(name);
}
if (missing.length) {
    console.error(`Missing symbols in upstream sprite: ${missing.join(", ")}`);
    process.exit(1);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">
    <defs>
        ${symbols.join("\n        ")}
    </defs>
</svg>
`;

const union = names.map(n => `    | "${n}"`).join("\n");
const types = `// Generated by scripts/build-icons.mjs — do not edit by hand.
export type IconName =
${union};
`;

mkdirSync(dirname(spriteOut), { recursive: true });
writeFileSync(spriteOut, sprite);
writeFileSync(typeOut, types);
console.log(`Wrote ${symbols.length} symbols -> ${spriteOut}`);
console.log(`Wrote IconName (${names.length} names) -> ${typeOut}`);
